def CONFIG_FILE = 'service.yaml'
def JAR_FILE = 'lite-country-service-1.0-SNAPSHOT.jar'

stage 'dev-service-build'
node {
    withEnv(["CONFIG_FILE=${CONFIG_FILE}", "JAR_FILE=${JAR_FILE}"]) {
        deleteDir()
        git poll: true, changelog: true, credentialsId: "${GIT_CREDENTIALS}", url: "${GIT_URL}"
        sh 'chmod 777 gradlew'
        sh './gradlew build'
        sh 'cp config/$CONFIG_FILE docker'
        sh 'cp build/libs/$JAR_FILE docker'
        archive 'docker/**'
    }

    step([$class: 'JUnitResultArchiver', testResults: 'build/test-results/**/*.xml'])
}

stage 'dev-docker-build'
build job: 'docker-build', parameters: [
    [$class: 'StringParameterValue', name: 'SERVICE_BUILD_JOB', value: "${env.JOB_NAME}"],
    [$class: 'StringParameterValue', name: 'IMAGE_NAME', value: 'country-service']
]

