cacheExpirySeconds: 86400
countryCacheJobCron: 0 0 0 * * ? # run at midnight everyday

spireClientUserName: "${SPIRE_CLIENT_USERNAME}"
spireClientPassword: "${SPIRE_CLIENT_PASSWORD}"
spireClientUrl: "${SPIRE_CLIENT_URL}"

server:
  type: default
  applicationConnectors:
    - type: http
      port: ${PORT}

logging:
  level: INFO
  appenders:
    - type: console
      includeCallerData : true
      logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"
  loggers:
    "uk.gov.bis.lite.common.spire.client.SpireClient": WARN
    "org.skife.jdbi.v2": TRACE

database:
  driverClass: org.postgresql.Driver
  url: "${VCAP_JDBC_URL}"
  schema: "${DATABASE_SCHEMA}"
  #user: postgres
  #password: password
  properties:
    charSet: UTF-8
  maxWaitForConnection: 30s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: ${DB_POOL_MIN_SIZE}
  maxSize: ${DB_POOL_MAX_SIZE}
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

adminLogin: "${ADMIN_LOGIN}"
adminPassword: "${ADMIN_PASSWORD}"

serviceLogin: "${SERVICE_LOGIN}"
servicePassword: "${SERVICE_PASSWORD}"