cacheExpirySeconds: 86400
countryCacheJobCron: 0 0 0 * * ? # run at midnight everyday

spireClientUserName: bisuat.api@test.com
spireClientPassword: sp1reUAT
#spireClientUrl: http://service-mocking.svc.dev.licensing.service.trade.gov.uk.test/spire/fox/ispire/
spireClientUrl: https://www.spiretest.trade.gov.uk/spireuat/fox/ispire/

server:
  type: default
  applicationConnectors:
    - type: http
      port: ${PORT}

logging:
  level: INFO
  appenders:
    - type: console
      includeCallerData : true
      logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"
  loggers:
    "uk.gov.bis.lite.common.spire.client.SpireClient": WARN
    "org.skife.jdbi.v2": TRACE

database:
  driverClass: org.postgresql.Driver
  url: ${VCAP_JDBC_URL}
  schema: countrysvc
  #user: postgres
  #password: password
  properties:
    charSet: UTF-8
  maxWaitForConnection: 30s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

adminLogin: user
adminPassword: password