cacheExpirySeconds: 86400
countryListCacheJobCron: 0 0 0 * * ? # run at midnight everyday

spireClientUserName: spire_username
spireClientPassword: spire_password
spireClientUrl: http://service-mocking.svc.dev.licensing.service.trade.gov.uk.test/spire/fox/ispire/

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080

logging:
  level: INFO
  appenders:
    - type: console
      includeCallerData : true
      logFormat: "[%mdc{corrID}] %d [%p] %marker %logger %m%n"