cacheExpirySeconds: 86400

countryListCacheJobCron: 0 0 0 * * ? # run at midnight everyday

countryListCacheRetryJobCron: 0 0/15 * * * ? # retry every 15 mins

soapAction: ${env.SPIRE_SOAP_NAMESPACE}

soapUrl: ${env.SPIRE_SOAP_ENDPOINT}

soapNamespace: ${env.SPIRE_SOAP_NAMESPACE}

spireCredentials: ${env.SPIRE_CREDENTIALS}

server:
  type: default
  applicationConnectors:
    - type: http
      port: ${env.PORT}

logging:

  level: INFO

  appenders:
    - type: file
      # The file to which current statements will be logged.
      currentLogFilename: ./logs/${env.LOG_FILE}.log

      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      archivedLogFilenamePattern: ./logs/${env.LOG_FILE}-%d.log.gz

      # The number of archived files to keep.
      archivedFileCount: 5

      # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
      timeZone: UTC