stage 'dev-build'
node {
    withEnv(["CONFIG_FILE=${CONFIG_FILE}", "JAR_FILE=${JAR_FILE}"]) {
        deleteDir()
        git poll: true, changelog: true, credentialsId: "${GIT_CREDENTIALS}", url: "${GIT_URL}"
        sh 'chmod 777 gradlew'
        sh './gradlew build'
        sh 'cp config/$CONFIG_FILE docker'
        sh 'cp build/libs/$JAR_FILE docker'
    }
}

stage 'dev-build-docker'
node {
    withEnv(["SERVICE_NAME=${SERVICE_NAME}", "JAR_FILE=${JAR_FILE}", "CONFIG_FILE=${CONFIG_FILE}", "PORT=${PORT}", "IMAGE_NAME=${IMAGE_NAME}"]) {
        sh '/docker/docker build --build-arg SERVICE_NAME=$SERVICE_NAME --build-arg JAR_FILE=$JAR_FILE --build-arg CONFIG_FILE=$CONFIG_FILE --build-arg PORT=$PORT -f docker/Dockerfile -t $IMAGE_NAME:$BUILD_NUMBER .'
        sh '/docker/docker push $IMAGE_NAME:$BUILD_NUMBER'
    }
}


