INSERT INTO COUNTRY_DATA (COUNTRY_REF, SYNONYMS) VALUES ('CTRY3', '["United Arab Emirates","UAE","U.A.E."]');
INSERT INTO COUNTRY_DATA (COUNTRY_REF, SYNONYMS) VALUES ('CTRY1434', '["French Republic"]')
