INSERT INTO SYNONYMS (COUNTRY_REF, SYNONYM) VALUES ('CTRY3', 'United Arab Emirates');
INSERT INTO SYNONYMS (COUNTRY_REF, SYNONYM) VALUES ('CTRY3', 'UAE');
INSERT INTO SYNONYMS (COUNTRY_REF, SYNONYM) VALUES ('CTRY3', 'U.A.E.');
INSERT INTO SYNONYMS (COUNTRY_REF, SYNONYM) VALUES ('CTRY1434', 'French Republic')
